import { Inter } from "next/font/google";
import "./globals.css";
import Navigetions from "@/components/shered/navigetion/Navigetions";
import { Container } from "@mui/material";
import Footer from "@/components/shered/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-r from-[#0f0715]  to-[#2a1454] min-h-screen text-white">
          <Navigetions />
          <div className="min-h-screen">{children}</div>
          <Footer></Footer>
        </div>

      </body>
    </html>
  );
}
